import {AppointmentData} from "../Common/Types/types";

const FakeAppointmentsArray : Array<AppointmentData> = [
  {
    "id": 66,
    "patientId": 74,
    "therapyId": 30,
    "beginDate": "2023-06-19",
    "beginTime": "09:15:00",
    "beginAt": "2023-06-19 09:15:00",
    "status": 0,
    "endDate": "2023-06-19",
    "endTime": "10:45:00",
    "endAt": "2023-06-19 10:45:00",
    "statusStr": "Scheduled",
    "therapy": {
      "id": 30,
      "name": "Pain Therapy 3",
      "description": "Et aliquam itaque ea sunt consequatur reiciendis consequatur. Non occaecati blanditiis fugit officiis et saepe officiis. Expedita commodi illum amet omnis. Ut voluptas non aut facilis neque.\n\nSunt quos ea incidunt praesentium ipsa reprehenderit voluptas. Consequatur saepe ut officiis nihil eius. Tempora minus nobis quam eum.",
      "category": "Standard",
      "minDuration": 25,
      "maxDuration": 90,
      "doctorId": 17,
      "photos_count": 4,
      "appointments_count": 2,
      "photos": [
        "http://localhost:8000/f/therapy/06.png",
        "http://localhost:8000/f/therapy/03.png",
        "http://localhost:8000/f/therapy/05.png",
        "http://localhost:8000/f/therapy/05.png"
      ],
      "doctor": {
        "id": 17,
        "type": 1,
        "name": "Dennis Stoltenberg",
        "bio": "Facilis amet eligendi at exercitationem reprehenderit. Minima est at assumenda vitae excepturi non ut ducimus. Rerum vitae molestiae quod culpa. Temporibus doloremque sint ut incidunt. Consequuntur cum voluptatibus qui repellat assumenda.",
        "avatarUrl": "http://localhost:8000/f/people/Ava.png",
        "skill_mental": true,
        "skill_beauty": false,
        "skill_blood": true,
        "typeStr": "Nurse",
        "isDoctor": false,
        "isNurse": true
      }
    },
    "patient": {
      "id": 74,
      "name": "Katheryn",
      "surname": "Friesen",
      "sexType": 0,
      "birthday": "1988-11-25",
      "email": "simonis.mylene@kautzer.com",
      "status": 1,
      "phoneCountryCode": "+43",
      "phoneNumber": "5.494.1150",
      "appointments_count": 2,
      "open_appointments_count": 2,
      "sexTypeStr": "Male",
      "fullName": "Katheryn Friesen",
      "isMale": true,
      "isFemale": false,
      "statusStr": "Hold",
      "isActive": false,
      "isHold": true
    }
  },
  {
    "id": 12,
    "patientId": 9,
    "therapyId": 4,
    "beginDate": "2023-06-19",
    "beginTime": "12:00:00",
    "beginAt": "2023-06-19 12:00:00",
    "status": 0,
    "endDate": "2023-06-19",
    "endTime": "13:30:00",
    "endAt": "2023-06-19 13:30:00",
    "statusStr": "Scheduled",
    "therapy": {
      "id": 4,
      "name": "Pain Therapy 1",
      "description": "Dolores deleniti ratione ea. Ullam aliquid ut magnam alias nesciunt explicabo. Id est saepe officiis magni deserunt debitis. Itaque dolore et animi.\n\nEst nihil quia dolorem corrupti qui. Harum consectetur ratione eum delectus. Ut sapiente qui eaque qui voluptate cumque.",
      "category": "Head",
      "minDuration": 10,
      "maxDuration": 90,
      "doctorId": 1,
      "photos_count": 4,
      "appointments_count": 5,
      "photos": [
        "http://localhost:8000/f/therapy/06.png",
        "http://localhost:8000/f/therapy/05.png",
        "http://localhost:8000/f/therapy/04.png",
        "http://localhost:8000/f/therapy/03.png"
      ],
      "doctor": {
        "id": 1,
        "type": 1,
        "name": "Ian Denesik",
        "bio": "Consequatur fugit et at explicabo eum optio. Autem ratione omnis commodi qui quis reiciendis. Veniam officiis ducimus deserunt unde laboriosam optio asperiores. Ipsam rem harum aperiam accusantium nesciunt magnam et ipsum. Porro earum qui aut alias ut sed.",
        "avatarUrl": "http://localhost:8000/f/people/Ava.png",
        "skill_mental": true,
        "skill_beauty": false,
        "skill_blood": false,
        "typeStr": "Nurse",
        "isDoctor": false,
        "isNurse": true
      }
    },
    "patient": {
      "id": 9,
      "name": "Rosemarie",
      "surname": "Hintz",
      "sexType": 0,
      "birthday": "1987-09-07",
      "email": "mvon@gmail.com",
      "status": 0,
      "phoneCountryCode": "+43",
      "phoneNumber": ") 980-3334",
      "appointments_count": 3,
      "open_appointments_count": 3,
      "sexTypeStr": "Male",
      "fullName": "Rosemarie Hintz",
      "isMale": true,
      "isFemale": false,
      "statusStr": "Active",
      "isActive": true,
      "isHold": false
    }
  },
  {
    "id": 122,
    "patientId": 80,
    "therapyId": 6,
    "beginDate": "2023-06-19",
    "beginTime": "14:00:00",
    "beginAt": "2023-06-19 14:00:00",
    "status": 0,
    "endDate": "2023-06-19",
    "endTime": "15:00:00",
    "endAt": "2023-06-19 15:00:00",
    "statusStr": "Scheduled",
    "therapy": {
      "id": 6,
      "name": "Pain Therapy 2",
      "description": "Fugit fuga enim sunt laudantium sapiente dolorem officia. Qui ut perspiciatis est.\n\nOmnis vel sint deleniti. Qui atque voluptatibus velit vero sint atque. Hic quia inventore repudiandae sit et.",
      "category": "Standard",
      "minDuration": 25,
      "maxDuration": 60,
      "doctorId": 18,
      "photos_count": 3,
      "appointments_count": 4,
      "photos": [
        "http://localhost:8000/f/therapy/01.png",
        "http://localhost:8000/f/therapy/05.png",
        "http://localhost:8000/f/therapy/02.png"
      ],
      "doctor": {
        "id": 18,
        "type": 1,
        "name": "Ludwig Champlin",
        "bio": "Delectus et tempora facilis. Voluptatem est nulla sed eius fugit. Tempore et iusto natus rerum tenetur. Voluptate error quis voluptatum nemo non sapiente. Quasi corrupti ut necessitatibus et aut excepturi et.",
        "avatarUrl": "http://localhost:8000/f/people/Lucas.png",
        "skill_mental": true,
        "skill_beauty": false,
        "skill_blood": true,
        "typeStr": "Nurse",
        "isDoctor": false,
        "isNurse": true
      }
    },
    "patient": {
      "id": 80,
      "name": "Oral",
      "surname": "Reichert",
      "sexType": 1,
      "birthday": "1985-10-24",
      "email": "kirk01@yahoo.com",
      "status": 1,
      "phoneCountryCode": "+43",
      "phoneNumber": ") 974-6504",
      "appointments_count": 4,
      "open_appointments_count": 4,
      "sexTypeStr": "Female",
      "fullName": "Oral Reichert",
      "isMale": false,
      "isFemale": true,
      "statusStr": "Hold",
      "isActive": false,
      "isHold": true
    }
  },
  {
    "id": 97,
    "patientId": 51,
    "therapyId": 20,
    "beginDate": "2023-06-19",
    "beginTime": "14:15:00",
    "beginAt": "2023-06-19 14:15:00",
    "status": 0,
    "endDate": "2023-06-19",
    "endTime": "15:15:00",
    "endAt": "2023-06-19 15:15:00",
    "statusStr": "Scheduled",
    "therapy": {
      "id": 20,
      "name": "Pain Therapy 1",
      "description": "Quo eum aliquam et ut. Saepe accusantium et voluptatum nostrum totam fugit. Voluptate ut fugiat earum nihil. Cupiditate placeat velit eos.\n\nPlaceat labore vel cumque quod aut. Accusantium sed aut et praesentium deleniti eos enim et. Adipisci et aut corporis nobis est odio. Sit et officia amet ut quisquam itaque.",
      "category": "Head",
      "minDuration": 25,
      "maxDuration": 60,
      "doctorId": 12,
      "photos_count": 7,
      "appointments_count": 2,
      "photos": [
        "http://localhost:8000/f/therapy/04.png",
        "http://localhost:8000/f/therapy/01.png",
        "http://localhost:8000/f/therapy/02.png",
        "http://localhost:8000/f/therapy/02.png",
        "http://localhost:8000/f/therapy/05.png",
        "http://localhost:8000/f/therapy/05.png",
        "http://localhost:8000/f/therapy/04.png"
      ],
      "doctor": {
        "id": 12,
        "type": 1,
        "name": "Mr. Erik Gutmann PhD",
        "bio": "Error aut odit eos ut voluptatum rerum delectus molestiae. Ratione rem ab molestiae minima pariatur ab qui. Unde aperiam nulla sit voluptas error aut. Aut eum modi velit minus reiciendis.",
        "avatarUrl": "http://localhost:8000/f/people/Liam.png",
        "skill_mental": false,
        "skill_beauty": true,
        "skill_blood": false,
        "typeStr": "Nurse",
        "isDoctor": false,
        "isNurse": true
      }
    },
    "patient": {
      "id": 51,
      "name": "Jimmie",
      "surname": "Buckridge",
      "sexType": 1,
      "birthday": "1985-03-21",
      "email": "lon.lockman@wyman.com",
      "status": 0,
      "phoneCountryCode": "+43",
      "phoneNumber": "8.497.5213",
      "appointments_count": 4,
      "open_appointments_count": 2,
      "sexTypeStr": "Female",
      "fullName": "Jimmie Buckridge",
      "isMale": false,
      "isFemale": true,
      "statusStr": "Active",
      "isActive": true,
      "isHold": false
    }
  },
  {
    "id": 46,
    "patientId": 78,
    "therapyId": 16,
    "beginDate": "2023-06-19",
    "beginTime": "17:00:00",
    "beginAt": "2023-06-19 17:00:00",
    "status": 0,
    "endDate": "2023-06-19",
    "endTime": "18:15:00",
    "endAt": "2023-06-19 18:15:00",
    "statusStr": "Scheduled",
    "therapy": {
      "id": 16,
      "name": "Pain Therapy 3",
      "description": "Est ut temporibus et harum aut debitis et autem. Dolorem et porro laborum corporis repellat. Saepe sit iste praesentium voluptatibus est eum voluptatem cupiditate. Repudiandae quam vel nulla voluptatibus qui.\n\nQui ut fugit vel ut voluptas nobis et non. Harum odit qui minima molestiae occaecati consequatur. Ab voluptatem non rerum fugit et incidunt. Enim vel iure quos id harum. Vel eaque voluptates placeat mollitia maiores at reprehenderit et.",
      "category": "Standard",
      "minDuration": 30,
      "maxDuration": 75,
      "doctorId": 12,
      "photos_count": 3,
      "appointments_count": 7,
      "photos": [
        "http://localhost:8000/f/therapy/02.png",
        "http://localhost:8000/f/therapy/05.png",
        "http://localhost:8000/f/therapy/06.png"
      ],
      "doctor": {
        "id": 12,
        "type": 1,
        "name": "Mr. Erik Gutmann PhD",
        "bio": "Error aut odit eos ut voluptatum rerum delectus molestiae. Ratione rem ab molestiae minima pariatur ab qui. Unde aperiam nulla sit voluptas error aut. Aut eum modi velit minus reiciendis.",
        "avatarUrl": "http://localhost:8000/f/people/Liam.png",
        "skill_mental": false,
        "skill_beauty": true,
        "skill_blood": false,
        "typeStr": "Nurse",
        "isDoctor": false,
        "isNurse": true
      }
    },
    "patient": {
      "id": 78,
      "name": "Trisha",
      "surname": "Wiegand",
      "sexType": 0,
      "birthday": "1998-02-24",
      "email": "nbeer@langworth.com",
      "status": 1,
      "phoneCountryCode": "+43",
      "phoneNumber": "0-705-1489",
      "appointments_count": 1,
      "open_appointments_count": 1,
      "sexTypeStr": "Male",
      "fullName": "Trisha Wiegand",
      "isMale": true,
      "isFemale": false,
      "statusStr": "Hold",
      "isActive": false,
      "isHold": true
    }
  },
    {
      "id": 75,
      "patientId": 28,
      "therapyId": 14,
      "beginDate": "2023-06-22",
      "beginTime": "12:00:00",
      "beginAt": "2023-06-22 12:00:00",
      "status": 0,
      "endDate": "2023-06-22",
      "endTime": "13:30:00",
      "endAt": "2023-06-22 13:30:00",
      "statusStr": "Scheduled",
      "therapy": {
        "id": 14,
        "name": "Pain Therapy 2",
        "description": "Aperiam quam sunt adipisci est. Aut eius vel et tempore tempore consequatur. Aut eum qui sunt quis ab voluptas blanditiis. Rem a minus impedit laborum aut laboriosam culpa.\n\nDelectus ipsa autem quisquam. Enim commodi soluta impedit vel natus repellendus. Et tempore dolorem eos.",
        "category": "Full Body",
        "minDuration": 25,
        "maxDuration": 90,
        "doctorId": 4,
        "photos_count": 2,
        "appointments_count": 2,
        "photos": [
          "http://localhost:8000/f/therapy/06.png",
          "http://localhost:8000/f/therapy/01.png"
        ],
        "doctor": {
          "id": 4,
          "type": 1,
          "name": "Mr. Orin Schultz",
          "bio": "Est quidem commodi omnis ex est qui eius. Adipisci dicta et dolor veniam sunt. Quis a qui quidem nobis. Saepe et totam aperiam quibusdam.",
          "avatarUrl": "http://localhost:8000/f/people/Oliver.png",
          "skill_mental": false,
          "skill_beauty": true,
          "skill_blood": false,
          "typeStr": "Nurse",
          "isDoctor": false,
          "isNurse": true
        }
      },
      "patient": {
        "id": 28,
        "name": "Kaylie",
        "surname": "Schuppe",
        "sexType": 0,
        "birthday": "1990-04-22",
        "email": "melany04@gmail.com",
        "status": 0,
        "phoneCountryCode": "+43",
        "phoneNumber": "2-239-6588",
        "appointments_count": 4,
        "open_appointments_count": 3,
        "sexTypeStr": "Male",
        "fullName": "Kaylie Schuppe",
        "isMale": true,
        "isFemale": false,
        "statusStr": "Active",
        "isActive": true,
        "isHold": false
      }
    },
    {
      "id": 119,
      "patientId": 58,
      "therapyId": 15,
      "beginDate": "2023-06-22",
      "beginTime": "12:00:00",
      "beginAt": "2023-06-22 12:00:00",
      "status": 0,
      "endDate": "2023-06-22",
      "endTime": "13:30:00",
      "endAt": "2023-06-22 13:30:00",
      "statusStr": "Scheduled",
      "therapy": {
        "id": 15,
        "name": "Pain Therapy 1",
        "description": "Similique placeat libero similique enim est. Accusantium ullam nulla corporis. Nostrum distinctio impedit quia cum a. Illum quidem eum quasi nobis.\n\nAt voluptas atque dicta rerum id quas. Totam excepturi neque cum est. Culpa vitae autem earum sunt.",
        "category": "Head",
        "minDuration": 30,
        "maxDuration": 90,
        "doctorId": 10,
        "photos_count": 4,
        "appointments_count": 8,
        "photos": [
          "http://localhost:8000/f/therapy/03.png",
          "http://localhost:8000/f/therapy/04.png",
          "http://localhost:8000/f/therapy/06.png",
          "http://localhost:8000/f/therapy/04.png"
        ],
        "doctor": {
          "id": 10,
          "type": 0,
          "name": "Jayda Schaefer",
          "bio": "Sit reiciendis neque sint libero voluptatum inventore expedita. Consequatur consectetur eaque eum id. Voluptas iure excepturi soluta velit neque dicta facilis. Libero et cupiditate ipsum molestias officiis a. Nulla qui et ea ab.",
          "avatarUrl": "http://localhost:8000/f/people/Olivia.png",
          "skill_mental": false,
          "skill_beauty": true,
          "skill_blood": false,
          "typeStr": "Doctor",
          "isDoctor": true,
          "isNurse": false
        }
      },
      "patient": {
        "id": 58,
        "name": "Orin",
        "surname": "Marquardt",
        "sexType": 1,
        "birthday": "1996-09-10",
        "email": "daphne17@conn.biz",
        "status": 0,
        "phoneCountryCode": "+43",
        "phoneNumber": ") 207-2226",
        "appointments_count": 2,
        "open_appointments_count": 2,
        "sexTypeStr": "Female",
        "fullName": "Orin Marquardt",
        "isMale": false,
        "isFemale": true,
        "statusStr": "Active",
        "isActive": true,
        "isHold": false
      }
    },
    {
      "id": 115,
      "patientId": 80,
      "therapyId": 40,
      "beginDate": "2023-06-22",
      "beginTime": "12:30:00",
      "beginAt": "2023-06-22 12:30:00",
      "status": 0,
      "endDate": "2023-06-22",
      "endTime": "13:30:00",
      "endAt": "2023-06-22 13:30:00",
      "statusStr": "Scheduled",
      "therapy": {
        "id": 40,
        "name": "Pain Therapy 3",
        "description": "Soluta error expedita labore inventore distinctio temporibus. Consequatur adipisci veritatis et tenetur iusto. Eaque qui nulla nemo sunt. Dolores in quibusdam voluptates nostrum ab ut et magni.\n\nLaboriosam beatae tenetur aliquid sint magnam dolorem id. Doloremque quas corrupti atque dolores eum minus. Non a dolores quod magni itaque. Facere veritatis consequatur dolores quibusdam.",
        "category": "Legs",
        "minDuration": 10,
        "maxDuration": 60,
        "doctorId": 16,
        "photos_count": 2,
        "appointments_count": 2,
        "photos": [
          "http://localhost:8000/f/therapy/01.png",
          "http://localhost:8000/f/therapy/02.png"
        ],
        "doctor": {
          "id": 16,
          "type": 0,
          "name": "Destiney Buckridge",
          "bio": "Dolor doloremque enim veniam error. Et aut est ut repellat. Ex eos voluptatem nihil error distinctio impedit. Atque repudiandae mollitia accusamus perferendis laboriosam.",
          "avatarUrl": "http://localhost:8000/f/people/Elijah.png",
          "skill_mental": true,
          "skill_beauty": false,
          "skill_blood": true,
          "typeStr": "Doctor",
          "isDoctor": true,
          "isNurse": false
        }
      },
      "patient": {
        "id": 80,
        "name": "Oral",
        "surname": "Reichert",
        "sexType": 1,
        "birthday": "1985-10-24",
        "email": "kirk01@yahoo.com",
        "status": 1,
        "phoneCountryCode": "+43",
        "phoneNumber": ") 974-6504",
        "appointments_count": 4,
        "open_appointments_count": 4,
        "sexTypeStr": "Female",
        "fullName": "Oral Reichert",
        "isMale": false,
        "isFemale": true,
        "statusStr": "Hold",
        "isActive": false,
        "isHold": true
      }
    },
    {
      "id": 82,
      "patientId": 15,
      "therapyId": 5,
      "beginDate": "2023-06-22",
      "beginTime": "15:15:00",
      "beginAt": "2023-06-22 15:15:00",
      "status": 0,
      "endDate": "2023-06-22",
      "endTime": "16:15:00",
      "endAt": "2023-06-22 16:15:00",
      "statusStr": "Scheduled",
      "therapy": {
        "id": 5,
        "name": "Pain Therapy 2",
        "description": "Amet cum sed itaque. Eos nulla quod architecto explicabo cum laborum excepturi.\n\nVoluptas qui in eum omnis. Eligendi in et non. Esse ea quisquam temporibus qui. Temporibus architecto incidunt laboriosam non quae quae. Hic molestias accusantium fugit.",
        "category": "Standard",
        "minDuration": 10,
        "maxDuration": 60,
        "doctorId": 15,
        "photos_count": 5,
        "appointments_count": 4,
        "photos": [
          "http://localhost:8000/f/therapy/02.png",
          "http://localhost:8000/f/therapy/04.png",
          "http://localhost:8000/f/therapy/03.png",
          "http://localhost:8000/f/therapy/02.png",
          "http://localhost:8000/f/therapy/06.png"
        ],
        "doctor": {
          "id": 15,
          "type": 0,
          "name": "Elisabeth Simonis",
          "bio": "Perspiciatis veniam ut omnis voluptatem. Vel reprehenderit sit voluptatum ut nesciunt facilis. Omnis praesentium excepturi occaecati odit voluptatum odit error. Ratione quas earum dolor.",
          "avatarUrl": "http://localhost:8000/f/people/Liam.png",
          "skill_mental": true,
          "skill_beauty": true,
          "skill_blood": false,
          "typeStr": "Doctor",
          "isDoctor": true,
          "isNurse": false
        }
      },
      "patient": {
        "id": 15,
        "name": "Antonio",
        "surname": "Leffler",
        "sexType": 1,
        "birthday": "1998-04-27",
        "email": "xluettgen@kessler.biz",
        "status": 0,
        "phoneCountryCode": "+43",
        "phoneNumber": "9-216-3943",
        "appointments_count": 3,
        "open_appointments_count": 3,
        "sexTypeStr": "Female",
        "fullName": "Antonio Leffler",
        "isMale": false,
        "isFemale": true,
        "statusStr": "Active",
        "isActive": true,
        "isHold": false
      }
    },
    {
      "id": 98,
      "patientId": 5,
      "therapyId": 20,
      "beginDate": "2023-06-22",
      "beginTime": "15:30:00",
      "beginAt": "2023-06-22 15:30:00",
      "status": 0,
      "endDate": "2023-06-22",
      "endTime": "16:30:00",
      "endAt": "2023-06-22 16:30:00",
      "statusStr": "Scheduled",
      "therapy": {
        "id": 20,
        "name": "Pain Therapy 1",
        "description": "Quo eum aliquam et ut. Saepe accusantium et voluptatum nostrum totam fugit. Voluptate ut fugiat earum nihil. Cupiditate placeat velit eos.\n\nPlaceat labore vel cumque quod aut. Accusantium sed aut et praesentium deleniti eos enim et. Adipisci et aut corporis nobis est odio. Sit et officia amet ut quisquam itaque.",
        "category": "Head",
        "minDuration": 25,
        "maxDuration": 60,
        "doctorId": 12,
        "photos_count": 7,
        "appointments_count": 2,
        "photos": [
          "http://localhost:8000/f/therapy/04.png",
          "http://localhost:8000/f/therapy/01.png",
          "http://localhost:8000/f/therapy/02.png",
          "http://localhost:8000/f/therapy/02.png",
          "http://localhost:8000/f/therapy/05.png",
          "http://localhost:8000/f/therapy/05.png",
          "http://localhost:8000/f/therapy/04.png"
        ],
        "doctor": {
          "id": 12,
          "type": 1,
          "name": "Mr. Erik Gutmann PhD",
          "bio": "Error aut odit eos ut voluptatum rerum delectus molestiae. Ratione rem ab molestiae minima pariatur ab qui. Unde aperiam nulla sit voluptas error aut. Aut eum modi velit minus reiciendis.",
          "avatarUrl": "http://localhost:8000/f/people/Liam.png",
          "skill_mental": false,
          "skill_beauty": true,
          "skill_blood": false,
          "typeStr": "Nurse",
          "isDoctor": false,
          "isNurse": true
        }
      },
      "patient": {
        "id": 5,
        "name": "Harold",
        "surname": "Weissnat",
        "sexType": 1,
        "birthday": "2004-06-21",
        "email": "eli.keebler@effertz.info",
        "status": 0,
        "phoneCountryCode": "+43",
        "phoneNumber": ") 358-0673",
        "appointments_count": 4,
        "open_appointments_count": 3,
        "sexTypeStr": "Female",
        "fullName": "Harold Weissnat",
        "isMale": false,
        "isFemale": true,
        "statusStr": "Active",
        "isActive": true,
        "isHold": false
      }
    }
]



export default FakeAppointmentsArray
